### ISSUE TITLE
Remove FormatterKit 

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS-Shared#177]
This issue came up from: #176 
In order to get rid of FormatterKit we need to provide a relative date (1 day ago) alternative using '''DateComponentsFormatter'''. 

here is @stevebaranski [playground]("https://github.com/wordpress-mobile/WordPress-iOS-Shared/files/2815105/wp-ios-shared_pr-176.playground.zip") to illustrate that you can accomplish most of what needs to be done with DateComponentsFormatter. While the class evinces locale-sensitive intervals, it does not appear to be capable of adding the "ago" suffix either, which FormatterKit refers to as "idiomatic deictic expressions". 

_What we need to do_:
- Use the logic in mediumString method (NSDate + Helpers) for time relativity presentation while using the logic in the playground instead of TTTTimeIntervalFormatter.
- In WPiOS, transition callers of mediumString method to a new method that calls mediumString(), but also appends ago in a locale-sensitive way when the interval is in the past.
- Facilitate the addition of these localized strings.

**Comment by bummytime** [comment]
@yaelirub @stevebaranski Just stopping by to reference https://github.com/woocommerce/woocommerce-ios/pull/649 where we had to address this same issue in Woo. 

The present deictic expression definitely was problematic for the translators (see point 3 in https://github.com/woocommerce/woocommerce-ios/issues/620), so I ended up [exposing the entire phrase](https://github.com/woocommerce/woocommerce-ios/blob/develop/WooCommerce/Classes/Extensions/Date%2BWoo.swift#L75-L80) to the translators so they could bend it to their will. 😃 

I am on groundskeeping this week so I can dig into this.

**Comment by stevebaranski** [comment]
Thanks for this additional context @bummytime! Please let me know if I can help you or @yaelirub out.

**Comment by yaelirub** [comment]
Thanks so much @bummytime ! Let me know if I can help

**Comment by yaelirub** [comment]
Closing this one as a stale
